#! /bin/bash
# generated by collect_git_remote_add_recursively.sh

pushd $(dirname $0)                                                             2> /dev/null   > /dev/null
cd ..

mode="d"

getopts ":fqh" opt
#echo opt+arg = "$opt$OPTARG"
case "$opt$OPTARG" in
f )
  echo "--- check out master/HEAD before registering all git remotes ---"
  for (( i=OPTIND; i > 1; i-- )) do
    shift
  done
  #echo args: $@
  mode="f"

  git submodule sync
  git submodule update --init
  git submodule update --init --recursive

  util/git_checkout_submodules_head.sh
  ;;

"?" )
  echo "--- set up git remotes only ---"
  ;;

q )
  echo "--- set up git remotes only ---"
  for (( i=OPTIND; i > 1; i-- )) do
    shift
  done
  #echo args: $@
  mode="q"
  ;;

* )
  cat <<EOT
$0 [-f] [-q] [submodule-paths]

set up git remotes for any / all submodules.

-f       : 'full featured', i.e. check out the preferred branch for each submodule
           and register all submodule remotes.
-q       : 'quick', i.e. only register all submodule remotes.
submodule-paths
         : when you specify one or more submodule directories, than only the
           remotes for those submodules will be set up.
           This is optional; the default sets up the remotes for ALL submodules.

EOT
  exit
  ;;
esac


submodule=xxxxxx

# args: (path, name, repo, argc, argv...)
function register_remote {
    argc=$#
    argv=("$@")
    path=$1
    name=$2
    repo=$3
    #echo register_remote [$path] [$name] [$repo] [$argc] [...]

    # only when paths have been specified on the commandline do we check whether the given remote should be registered
    # (apart from the separate check to see if the submodule has actually been installed, see further below)
    if test $argc -gt 4 ; then
        hit=0
        for ((i=4; i < $argc; i++)); do
            #echo testing dir $i: ${argv[$i]}
            if test ${argv[$i]} = $path ; then
                hit=1
                break
            fi
        done
    else
        hit=1
    fi

    if test $hit -ne 0 ; then
        if test -d $path && test -s $path/.git ; then
            if test $submodule != $path ; then
                echo -------------------------------------------------------------------------------------
                echo submodule:: $path
                submodule=$path
            fi
            pushd $path                                                         2> /dev/null   > /dev/null
            if test "$mode" = "f" ; then
                git remote rm $name
            fi
            git remote add $name $repo
            popd                                                                2> /dev/null   > /dev/null
        fi
    fi
}






register_remote .                                                             AMAZNET                                  git@github.com:AMAZNET/intro.js.git                                              $# $@
register_remote .                                                             AlexanderKoehn                           git@github.com:AlexanderKoehn/intro.js.git                                       $# $@
register_remote .                                                             AndreRibeiroCampos                       git@github.com:AndreRibeiroCampos/intro.js.git                                   $# $@
register_remote .                                                             Angelmmiguel                             git@github.com:Angelmmiguel/intro.js.git                                         $# $@
register_remote .                                                             AppPress                                 git@github.com:AppPress/intro.js.git                                             $# $@
register_remote .                                                             Ax0ne                                    git@github.com:Ax0ne/intro.js.git                                                $# $@
register_remote .                                                             Blue-NET-Ready-Solutions                 git@github.com:Blue-NET-Ready-Solutions/intro.js.git                             $# $@
register_remote .                                                             BrianLaughlan                            git@github.com:BrianLaughlan/intro.js.git                                        $# $@
register_remote .                                                             CMS-Scripts                              git@github.com:CMS-Scripts/intro.js.git                                          $# $@
register_remote .                                                             CRM-Scripts                              git@github.com:CRM-Scripts/intro.js.git                                          $# $@
register_remote .                                                             Cangit                                   git@github.com:Cangit/intro.js.git                                               $# $@
register_remote .                                                             CarterCole                               git@github.com:CarterCole/intro.js.git                                           $# $@
register_remote .                                                             CesiumComputer                           git@github.com:CesiumComputer/intro.js.git                                       $# $@
register_remote .                                                             Chicuelo                                 git@github.com:Chicuelo/intro.js.git                                             $# $@
register_remote .                                                             Chris-Turnbull                           git@github.com:Chris-Turnbull/intro.js.git                                       $# $@
register_remote .                                                             ChristianBundy                           git@github.com:ChristianBundy/intro.js.git                                       $# $@
register_remote .                                                             Cloud9Trader                             git@github.com:Cloud9Trader/intro.js.git                                         $# $@
register_remote .                                                             Codetic                                  git@github.com:Codetic/intro.js.git                                              $# $@
register_remote .                                                             Codility                                 git@github.com:Codility/intro.js.git                                             $# $@
register_remote .                                                             Communote                                git@github.com:Communote/intro.js.git                                            $# $@
register_remote .                                                             Coursio                                  git@github.com:Coursio/intro.js.git                                              $# $@
register_remote .                                                             CreamCoderz                              git@github.com:CreamCoderz/intro.js.git                                          $# $@
register_remote .                                                             DanielePalombo                           git@github.com:DanielePalombo/intro.js.git                                       $# $@
register_remote .                                                             Delysid                                  git@github.com:Delysid/intro.js.git                                              $# $@
register_remote .                                                             EJanuszewski                             git@github.com:EJanuszewski/intro.js.git                                         $# $@
register_remote .                                                             EmailHamster                             git@github.com:EmailHamster/intro.js.git                                         $# $@
register_remote .                                                             Erez-IL                                  git@github.com:Erez-IL/intro.js.git                                              $# $@
register_remote .                                                             EricaChang                               git@github.com:EricaChang/intro.js.git                                           $# $@
register_remote .                                                             FeelgoodDE                               git@github.com:FeelgoodDE/intro.js.git                                           $# $@
register_remote .                                                             Fluotonic                                git@github.com:Fluotonic/intro.js.git                                            $# $@
register_remote .                                                             FrontEndTech                             git@github.com:FrontEndTech/intro.js.git                                         $# $@
register_remote .                                                             GerHobbelt                               git@github.com:GerHobbelt/intro.js.git                                           $# $@
register_remote .                                                             Giegling                                 git@github.com:Giegling/intro.js.git                                             $# $@
register_remote .                                                             Gigacodes                                git@github.com:Gigacodes/intro.js.git                                            $# $@
register_remote .                                                             GreatRepos                               git@github.com:GreatRepos/intro.js.git                                           $# $@
register_remote .                                                             GriggsResearchInstitute                  git@github.com:GriggsResearchInstitute/intro.js.git                              $# $@
register_remote .                                                             HanCong03                                git@github.com:HanCong03/intro.js.git                                            $# $@
register_remote .                                                             Hosting-Scripts                          git@github.com:Hosting-Scripts/intro.js.git                                      $# $@
register_remote .                                                             HostingScripts                           git@github.com:Hosting-Scripts/intro.js.git                                      $# $@
register_remote .                                                             IOKI                                     git@github.com:IOKI/intro.js.git                                                 $# $@
register_remote .                                                             Iguannaweb                               git@github.com:Iguannaweb/intro.js.git                                           $# $@
register_remote .                                                             Infratab                                 git@github.com:Infratab/intro.js.git                                             $# $@
register_remote .                                                             IsabelPalomar                            git@github.com:IsabelPalomar/intro.js.git                                        $# $@
register_remote .                                                             ItJiangHu                                git@github.com:ItJiangHu/intro.js.git                                            $# $@
register_remote .                                                             JDoe                                     git@github.com:JDoe/intro.js.git                                                 $# $@
register_remote .                                                             JoeDoyle23                               git@github.com:JoeDoyle23/intro.js.git                                           $# $@
register_remote .                                                             John-Chan                                git@github.com:John-Chan/intro.js.git                                            $# $@
register_remote .                                                             JohnAmican                               git@github.com:JohnAmican/intro.js.git                                           $# $@
register_remote .                                                             Jquery-Scripts                           git@github.com:Jquery-Scripts/intro.js.git                                       $# $@
register_remote .                                                             JqueryScripts                            git@github.com:Jquery-Scripts/intro.js.git                                       $# $@
register_remote .                                                             Justin-lu                                git@github.com:Justin-lu/intro.js.git                                            $# $@
register_remote .                                                             Justinlu                                 git@github.com:Justin-lu/intro.js.git                                            $# $@
register_remote .                                                             JvJefke                                  git@github.com:JvJefke/intro.js.git                                              $# $@
register_remote .                                                             KSDaemon                                 git@github.com:KSDaemon/intro.js.git                                             $# $@
register_remote .                                                             L0g1k                                    git@github.com:L0g1k/intro.js.git                                                $# $@
register_remote .                                                             LightPix                                 git@github.com:LightPix/intro.js.git                                             $# $@
register_remote .                                                             LittleBang                               git@github.com:LittleBang/intro.js.git                                           $# $@
register_remote .                                                             Mango-information-systems                git@github.com:Mango-information-systems/intro.js.git                            $# $@
register_remote .                                                             Meritts                                  git@github.com:Meritts/intro.js.git                                              $# $@
register_remote .                                                             MikeTheReader                            git@github.com:MikeTheReader/intro.js.git                                        $# $@
register_remote .                                                             MrGorki                                  git@github.com:MrGorki/intro.js.git                                              $# $@
register_remote .                                                             Naycon                                   git@github.com:Naycon/intro.js.git                                               $# $@
register_remote .                                                             Nyholm                                   git@github.com:Nyholm/intro.js.git                                               $# $@
register_remote .                                                             OpenGUI                                  git@github.com:OpenGUI/intro.js.git                                              $# $@
register_remote .                                                             OpenHosts                                git@github.com:OpenHosts/intro.js.git                                            $# $@
register_remote .                                                             OpenUX                                   git@github.com:OpenUX/intro.js.git                                               $# $@
register_remote .                                                             Orphist                                  git@github.com:Orphist/intro.js.git                                              $# $@
register_remote .                                                             PWRD                                     git@github.com:PWRD/intro.js.git                                                 $# $@
register_remote .                                                             PanosFirmpas                             git@github.com:PanosFirmpas/intro.js.git                                         $# $@
register_remote .                                                             PhilippSchreiber                         git@github.com:PhilippSchreiber/intro.js.git                                     $# $@
register_remote .                                                             Platane                                  git@github.com:Platane/intro.js.git                                              $# $@
register_remote .                                                             PortableSheep                            git@github.com:PortableSheep/intro.js.git                                        $# $@
register_remote .                                                             RUPOJS                                   git@github.com:RUPOJS/intro.js.git                                               $# $@
register_remote .                                                             RedJabber                                git@github.com:RedJabber/intro.js.git                                            $# $@
register_remote .                                                             RolePlayGateway                          git@github.com:RolePlayGateway/intro.js.git                                      $# $@
register_remote .                                                             SILL-BILL                                git@github.com:SILL-BILL/intro.js.git                                            $# $@
register_remote .                                                             SpektrumFM                               git@github.com:SpektrumFM/intro.js.git                                           $# $@
register_remote .                                                             Stellenticket                            git@github.com:Stellenticket/intro.js.git                                        $# $@
register_remote .                                                             StephanHoyer                             git@github.com:StephanHoyer/intro.js.git                                         $# $@
register_remote .                                                             Svish                                    git@github.com:Svish/intro.js.git                                                $# $@
register_remote .                                                             Syerram                                  git@github.com:Syerram/intro.js.git                                              $# $@
register_remote .                                                             TechnotronicOz                           git@github.com:TechnotronicOz/intro.js.git                                       $# $@
register_remote .                                                             Terrorboy                                git@github.com:Terrorboy/intro.js.git                                            $# $@
register_remote .                                                             TheDarkITA                               git@github.com:TheDarkITA/intro.js.git                                           $# $@
register_remote .                                                             TheX                                     git@github.com:TheX/intro.js.git                                                 $# $@
register_remote .                                                             Thinnies                                 git@github.com:Thinnies/intro.js.git                                             $# $@
register_remote .                                                             TrackIF                                  git@github.com:TrackIF/intro.js.git                                              $# $@
register_remote .                                                             Travel-Agent                             git@github.com:Travel-Agent/intro.js.git                                         $# $@
register_remote .                                                             Travel-Agent1                            git@github.com:Travel-Agent1/intro.js.git                                        $# $@
register_remote .                                                             Tsenzuk                                  git@github.com:Tsenzuk/intro.js.git                                              $# $@
register_remote .                                                             UXScripts                                git@github.com:UXScripts/intro.js.git                                            $# $@
register_remote .                                                             UiDesign                                 git@github.com:UiDesign/intro.js.git                                             $# $@
register_remote .                                                             Urigo                                    git@github.com:Urigo/intro.js.git                                                $# $@
register_remote .                                                             Web5design                               git@github.com:Web5design/intro.js.git                                           $# $@
register_remote .                                                             WebCreators                              git@github.com:WebCreators/intro.js.git                                          $# $@
register_remote .                                                             WebDevelopmentOnMac                      git@github.com:WebDevelopmentOnMac/intro.js.git                                  $# $@
register_remote .                                                             Wikimapia                                git@github.com:Wikimapia/intro.js.git                                            $# $@
register_remote .                                                             Wyndala                                  git@github.com:Wyndala/intro.js.git                                              $# $@
register_remote .                                                             Yaphats                                  git@github.com:Yaphats/intro.js.git                                              $# $@
register_remote .                                                             Yazalim                                  git@github.com:Yazalim/intro.js.git                                              $# $@
register_remote .                                                             ZuTa                                     git@github.com:ZuTa/intro.js.git                                                 $# $@
register_remote .                                                             abstractcodify                           git@github.com:abstractcodify/intro.js.git                                       $# $@
register_remote .                                                             adobi                                    git@github.com:adobi/intro.js.git                                                $# $@
register_remote .                                                             adrianp                                  git@github.com:adrianp/intro.js.git                                              $# $@
register_remote .                                                             alihaghighatkhah                         git@github.com:alihaghighatkhah/intro.js.git                                     $# $@
register_remote .                                                             alpha8                                   git@github.com:alpha8/intro.js.git                                               $# $@
register_remote .                                                             alvarotrigo                              git@github.com:alvarotrigo/intro.js.git                                          $# $@
register_remote .                                                             amerello                                 git@github.com:amerello/intro.js.git                                             $# $@
register_remote .                                                             amyerz                                   git@github.com:amyerz/intro.js.git                                               $# $@
register_remote .                                                             andragan                                 git@github.com:andragan/intro.js.git                                             $# $@
register_remote .                                                             andrewhathaway                           git@github.com:andrewhathaway/intro.js.git                                       $# $@
register_remote .                                                             angck                                    git@github.com:angck/intro.js.git                                                $# $@
register_remote .                                                             animadverto                              git@github.com:animadverto/intro.js.git                                          $# $@
register_remote .                                                             anujkumartech                            git@github.com:anujkumartech/intro.js.git                                        $# $@
register_remote .                                                             apatten                                  git@github.com:apatten/intro.js.git                                              $# $@
register_remote .                                                             aprilb                                   git@github.com:aprilb/intro.js.git                                               $# $@
register_remote .                                                             aramix                                   git@github.com:aramix/intro.js.git                                               $# $@
register_remote .                                                             arjshiv                                  git@github.com:arjshiv/intro.js.git                                              $# $@
register_remote .                                                             ashwinaggarwal                           git@github.com:ashwinaggarwal/intro.js.git                                       $# $@
register_remote .                                                             basarat                                  git@github.com:basarat/intro.js.git                                              $# $@
register_remote .                                                             bearoplane                               git@github.com:bearoplane/intro.js.git                                           $# $@
register_remote .                                                             bigeyedfishcreative                      git@github.com:bigeyedfishcreative/intro.js.git                                  $# $@
register_remote .                                                             bigpandaio                               git@github.com:bigpandaio/intro.js.git                                           $# $@
register_remote .                                                             bluehouse                                git@github.com:bluehouse/intro.js.git                                            $# $@
register_remote .                                                             bm-bookmarks                             git@github.com:bm-bookmarks/intro.js.git                                         $# $@
register_remote .                                                             bobstar                                  git@github.com:bobstar/intro.js.git                                              $# $@
register_remote .                                                             bokebi                                   git@github.com:bokebi/intro.js.git                                               $# $@
register_remote .                                                             borjacampina                             git@github.com:borjacampina/intro.js.git                                         $# $@
register_remote .                                                             bostikforever                            git@github.com:bostikforever/intro.js.git                                        $# $@
register_remote .                                                             bpartridge83                             git@github.com:bpartridge83/intro.js.git                                         $# $@
register_remote .                                                             bricezhou                                git@github.com:bricezhou/intro.js.git                                            $# $@
register_remote .                                                             brunowego                                git@github.com:brunowego/intro.js.git                                            $# $@
register_remote .                                                             bryantsai                                git@github.com:bryantsai/intro.js.git                                            $# $@
register_remote .                                                             buremba                                  git@github.com:buremba/dynamic-intro.js.git                                      $# $@
register_remote .                                                             c2y2                                     git@github.com:c2y2/intro.js.git                                                 $# $@
register_remote .                                                             calendar42                               git@github.com:calendar42/intro.js.git                                           $# $@
register_remote .                                                             camalot                                  git@github.com:camalot/intro.js.git                                              $# $@
register_remote .                                                             cbinsights                               git@github.com:cbinsights/intro.js.git                                           $# $@
register_remote .                                                             cesarandreu                              git@github.com:cesarandreu/intro.js.git                                          $# $@
register_remote .                                                             cf-ssharma                               git@github.com:cf-ssharma/intro.js.git                                           $# $@
register_remote .                                                             chancedai                                git@github.com:chancedai/intro.js.git                                            $# $@
register_remote .                                                             chris-armstrong                          git@github.com:chris-armstrong/intro.js.git                                      $# $@
register_remote .                                                             christianbundy                           git@github.com:christianbundy/intro.js.git                                       $# $@
register_remote .                                                             cnverg                                   git@github.com:cnverg/intro.js.git                                               $# $@
register_remote .                                                             codethirteen                             git@github.com:codethirteen/intro.js.git                                         $# $@
register_remote .                                                             connyay                                  git@github.com:connyay/intro.js.git                                              $# $@
register_remote .                                                             coolgggg                                 git@github.com:coolgggg/intro.js.git                                             $# $@
register_remote .                                                             cornerhome                               git@github.com:cornerhome/intro.js.git                                           $# $@
register_remote .                                                             croupier                                 git@github.com:croupier/intro.js.git                                             $# $@
register_remote .                                                             crowdlab                                 git@github.com:crowdlab/intro.js.git                                             $# $@
register_remote .                                                             cuicui777                                git@github.com:cuicui777/intro.js.git                                            $# $@
register_remote .                                                             danlevine                                git@github.com:danlevine/intro.js.git                                            $# $@
register_remote .                                                             davioliveira                             git@github.com:davioliveira/intro.js.git                                         $# $@
register_remote .                                                             deepakprabhakara                         git@github.com:deepakprabhakara/intro.js.git                                     $# $@
register_remote .                                                             dennis                                   git@github.com:dennis/intro.js.git                                               $# $@
register_remote .                                                             dexterliu                                git@github.com:dexterliu/intro.js.git                                            $# $@
register_remote .                                                             dfjones1981                              git@github.com:dfjones1981/intro.js.git                                          $# $@
register_remote .                                                             djjupa                                   git@github.com:djjupa/intro.js.git                                               $# $@
register_remote .                                                             doits                                    git@github.com:doits/intro.js.git                                                $# $@
register_remote .                                                             dominicbarnes                            git@github.com:dominicbarnes/intro.js.git                                        $# $@
register_remote .                                                             dosjota                                  git@github.com:dosjota/intro.js.git                                              $# $@
register_remote .                                                             dperish                                  git@github.com:dperish/intro.js.git                                              $# $@
register_remote .                                                             dreamtech                                git@github.com:dreamtech/intro.js.git                                            $# $@
register_remote .                                                             drodil                                   git@github.com:drodil/intro.js.git                                               $# $@
register_remote .                                                             dswen                                    git@github.com:dswen/intro.js.git                                                $# $@
register_remote .                                                             dziemian007                              git@github.com:dziemian007/intro.js.git                                          $# $@
register_remote .                                                             eightfivezero                            git@github.com:eightfivezero/intro.js.git                                        $# $@
register_remote .                                                             eikes                                    git@github.com:eikes/intro.js.git                                                $# $@
register_remote .                                                             eliovir                                  git@github.com:eliovir/intro.js.git                                              $# $@
register_remote .                                                             etoccalino                               git@github.com:etoccalino/intro.js.git                                           $# $@
register_remote .                                                             eugenicsarchivesca                       git@github.com:eugenicsarchivesca/intro.js.git                                   $# $@
register_remote .                                                             evach-vf                                 git@github.com:evach-vf/intro.js.git                                             $# $@
register_remote .                                                             ext0                                     git@github.com:ext0/intro.js.git                                                 $# $@
register_remote .                                                             fab34                                    git@github.com:fab34/intro.js.git                                                $# $@
register_remote .                                                             fedosov                                  git@github.com:fedosov/intro.js.git                                              $# $@
register_remote .                                                             ferleonardo                              git@github.com:ferleonardo/intro.js.git                                          $# $@
register_remote .                                                             fixate                                   git@github.com:fixate/introjs.git                                                $# $@
register_remote .                                                             fizerkhan                                git@github.com:fizerkhan/intro.js.git                                            $# $@
register_remote .                                                             flyer153                                 git@github.com:flyer153/intro.js.git                                             $# $@
register_remote .                                                             fny                                      git@github.com:fny/intro.js.git                                                  $# $@
register_remote .                                                             fromothers                               git@github.com:fromothers/intro.js.git                                           $# $@
register_remote .                                                             gabconcepcion                            git@github.com:gabconcepcion/intro.js.git                                        $# $@
register_remote .                                                             gabrielpoca                              git@github.com:gabrielpoca/intro.js.git                                          $# $@
register_remote .                                                             gerwald                                  git@github.com:gerwald/intro.js.git                                              $# $@
register_remote .                                                             greenmile                                git@github.com:greenmile/intro.js.git                                            $# $@
register_remote .                                                             guotingchaopr                            git@github.com:guotingchaopr/intro.js.git                                        $# $@
register_remote .                                                             hashtagify                               git@github.com:hashtagify/intro.js.git                                           $# $@
register_remote .                                                             heelhook                                 git@github.com:heelhook/intro.js.git                                             $# $@
register_remote .                                                             herrjemand                               git@github.com:herrjemand/intro.js.git                                           $# $@
register_remote .                                                             hillside-software                        git@github.com:hillside-software/intro.js.git                                    $# $@
register_remote .                                                             hillsidesoftware                         git@github.com:hillside-software/intro.js.git                                    $# $@
register_remote .                                                             hiprice                                  git@github.com:hiprice/intro.js.git                                              $# $@
register_remote .                                                             hopkinsth                                git@github.com:hopkinsth/intro.js.git                                            $# $@
register_remote .                                                             hugojay                                  git@github.com:hugojay/intro.js.git                                              $# $@
register_remote .                                                             iMezied                                  git@github.com:iMezied/intro.js.git                                              $# $@
register_remote .                                                             iSC-Networks-Videos                      git@github.com:iSC-Networks-Videos/intro.js.git                                  $# $@
register_remote .                                                             iSCGroup                                 git@github.com:iSCGroup/intro.js.git                                             $# $@
register_remote .                                                             iSCNetworksVideos                        git@github.com:iSC-Networks-Videos/intro.js.git                                  $# $@
register_remote .                                                             iamdenny                                 git@github.com:iamdenny/intro.js.git                                             $# $@
register_remote .                                                             iancanopy                                git@github.com:iancanopy/intro.js.git                                            $# $@
register_remote .                                                             icapitalnetwork                          git@github.com:icapitalnetwork/intro.js.git                                      $# $@
register_remote .                                                             ichikawatatsuya                          git@github.com:ichikawatatsuya/intro.js.git                                      $# $@
register_remote .                                                             ifchange                                 git@github.com:ifchange/intro.js.git                                             $# $@
register_remote .                                                             iman-mafi                                git@github.com:iman-mafi/intro.js.git                                            $# $@
register_remote .                                                             innov                                    git@github.com:inno-v/intro.js.git                                               $# $@
register_remote .                                                             innova-jp                                git@github.com:innova-jp/intro.js.git                                            $# $@
register_remote .                                                             innovajp                                 git@github.com:innova-jp/intro.js.git                                            $# $@
register_remote .                                                             interfaces                               git@github.com:interfaces/intro.js.git                                           $# $@
register_remote .                                                             ipiz                                     git@github.com:ipiz/intro.js.git                                                 $# $@
register_remote .                                                             jacano1969                               git@github.com:jacano1969/intro.js.git                                           $# $@
register_remote .                                                             jack126guy                               git@github.com:jack126guy/intro.js.git                                           $# $@
register_remote .                                                             jakeparis                                git@github.com:jakeparis/intro.js.git                                            $# $@
register_remote .                                                             jamesshore                               git@github.com:jamesshore/lab6_legacy_code.git                                   $# $@
register_remote .                                                             janposselt                               git@github.com:janposselt/intro.js.git                                           $# $@
register_remote .                                                             jasuca                                   git@github.com:jasuca/intro.js.git                                               $# $@
register_remote .                                                             javascript-forks                         git@github.com:javascript-forks/usablica.intro.js.git                            $# $@
register_remote .                                                             javascriptforks                          git@github.com:javascript-forks/usablica.intro.js.git                            $# $@
register_remote .                                                             jiacheo                                  git@github.com:jiacheo/intro.js.git                                              $# $@
register_remote .                                                             johan                                    git@github.com:johan--/intro.js.git                                              $# $@
register_remote .                                                             jorgenio                                 git@github.com:jorgenio/intro.js.git                                             $# $@
register_remote .                                                             juliosueiras                             git@github.com:juliosueiras/intro.js.git                                         $# $@
register_remote .                                                             k1000                                    git@github.com:k1000/intro.js.git                                                $# $@
register_remote .                                                             kevinold                                 git@github.com:kevinold/intro.js.git                                             $# $@
register_remote .                                                             kfrancis                                 git@github.com:kfrancis/intro.js.git                                             $# $@
register_remote .                                                             kleinph                                  git@github.com:kleinph/intro.js.git                                              $# $@
register_remote .                                                             kpourdeilami                             git@github.com:kpourdeilami/intro.js.git                                         $# $@
register_remote .                                                             kriorogue                                git@github.com:krio-rogue/intro.js.git                                           $# $@
register_remote .                                                             kstenschke                               git@github.com:kstenschke/intro.js.git                                           $# $@
register_remote .                                                             ktmswzw                                  git@github.com:ktmswzw/intro.js.git                                              $# $@
register_remote .                                                             kushalpandya                             git@github.com:kushalpandya/intro.js.git                                         $# $@
register_remote .                                                             kyoto                                    git@github.com:kyoto/intro.js.git                                                $# $@
register_remote .                                                             labithiotis                              git@github.com:labithiotis/intro.js.git                                          $# $@
register_remote .                                                             lebushi                                  git@github.com:lebushi/intro.js.git                                              $# $@
register_remote .                                                             ledbettj                                 git@github.com:ledbettj/intro.js.git                                             $# $@
register_remote .                                                             leejordan                                git@github.com:leejordan/intro.js.git                                            $# $@
register_remote .                                                             leodutra                                 git@github.com:leodutra/intro.js.git                                             $# $@
register_remote .                                                             leofontes                                git@github.com:leofontes/intro.js.git                                            $# $@
register_remote .                                                             leonardo031195                           git@github.com:leonardo031195/intro.js.git                                       $# $@
register_remote .                                                             lewising                                 git@github.com:lewis-ing/intro.js.git                                            $# $@
register_remote .                                                             lexfernandez                             git@github.com:lexfernandez/intro.js.git                                         $# $@
register_remote .                                                             lfbear                                   git@github.com:lfbear/intro.js.git                                               $# $@
register_remote .                                                             lihuazhang                               git@github.com:lihuazhang/intro.js.git                                           $# $@
register_remote .                                                             lipis                                    git@github.com:lipis/intro.js.git                                                $# $@
register_remote .                                                             littlebang                               git@github.com:littlebang/intro.js.git                                           $# $@
register_remote .                                                             ljspace                                  git@github.com:ljspace/intro.js.git                                              $# $@
register_remote .                                                             louis-sherren                            git@github.com:louis-sherren/intro.js.git                                        $# $@
register_remote .                                                             lovexiaobai                              git@github.com:lovexiaobai/intro.js.git                                          $# $@
register_remote .                                                             m8ms                                     git@github.com:m8ms/intro.js.git                                                 $# $@
register_remote .                                                             makkes                                   git@github.com:makkes/intro.js.git                                               $# $@
register_remote .                                                             mariomc                                  git@github.com:mariomc/intro.js.git                                              $# $@
register_remote .                                                             markbcapella                             git@github.com:markb-capella/intro.js.git                                        $# $@
register_remote .                                                             markparolisi                             git@github.com:markparolisi/intro.js.git                                         $# $@
register_remote .                                                             martinbede                               git@github.com:martin-bede/intro.js.git                                          $# $@
register_remote .                                                             mastermaiknemo                           git@github.com:mastermaiknemo/intro.js.git                                       $# $@
register_remote .                                                             matchu                                   git@github.com:matchu/intro.js.git                                               $# $@
register_remote .                                                             mattrepublic                             git@github.com:mattrepublic/intro.js.git                                         $# $@
register_remote .                                                             maurodias                                git@github.com:maurodias/intro.js.git                                            $# $@
register_remote .                                                             mdtrooper                                git@github.com:mdtrooper/intro.js.git                                            $# $@
register_remote .                                                             mendhak                                  git@github.com:mendhak/intro.js.git                                              $# $@
register_remote .                                                             mgiraldo                                 git@github.com:mgiraldo/intro.js.git                                             $# $@
register_remote .                                                             mhidou                                   git@github.com:mhidou/intro.js.git                                               $# $@
register_remote .                                                             micron                                   git@github.com:micron/intro.js.git                                               $# $@
register_remote .                                                             mikach                                   git@github.com:mikach/intro.js.git                                               $# $@
register_remote .                                                             mindblender                              git@github.com:mindblender/intro.js.git                                          $# $@
register_remote .                                                             minicstudio                              git@github.com:minicstudio/intro.js.git                                          $# $@
register_remote .                                                             mkarajohn                                git@github.com:mkarajohn/intro.js.git                                            $# $@
register_remote .                                                             mohammadamanalikhani                     git@github.com:mohammadamanalikhani/intro.js.git                                 $# $@
register_remote .                                                             monw3c                                   git@github.com:monw3c/intro.js.git                                               $# $@
register_remote .                                                             moomoohk                                 git@github.com:moomoohk/intro.js.git                                             $# $@
register_remote .                                                             morpheus-med                             git@github.com:morpheus-med/intro.js.git                                         $# $@
register_remote .                                                             mpmedia                                  git@github.com:mpmedia/intro.js.git                                              $# $@
register_remote .                                                             msakhawat                                git@github.com:msakhawat/intro.js.git                                            $# $@
register_remote .                                                             myusernamejeep                           git@github.com:myusernamejeep/intro.js.git                                       $# $@
register_remote .                                                             nanego                                   git@github.com:nanego/intro.js.git                                               $# $@
register_remote .                                                             nc-arima                                 git@github.com:nc-arima/intro.js.git                                             $# $@
register_remote .                                                             negative                                 git@github.com:negative/intro.js.git                                             $# $@
register_remote .                                                             nekitozzz                                git@github.com:nekitozzz/intro.js.git                                            $# $@
register_remote .                                                             nelsonwong1012                           git@github.com:nelsonwong1012/intro.js.git                                       $# $@
register_remote .                                                             nickbalestra                             git@github.com:nickbalestra/intro.js.git                                         $# $@
register_remote .                                                             nickpyren                                git@github.com:nickpyren/intro.js.git                                            $# $@
register_remote .                                                             niklas-andersson-stratsys                git@github.com:niklas-andersson-stratsys/intro.js.git                            $# $@
register_remote .                                                             ninjaas                                  git@github.com:ninjaas/intro.js.git                                              $# $@
register_remote .                                                             ninjastack                               git@github.com:ninjastack/intro.js.git                                           $# $@
register_remote .                                                             nmall                                    git@github.com:nmall/intro.js.git                                                $# $@
register_remote .                                                             noammohr                                 git@github.com:noammohr/intro.js.git                                             $# $@
register_remote .                                                             olmec-akeru                              git@github.com:olmec-akeru/intro.js.git                                          $# $@
register_remote .                                                             oyatsugoro                               git@github.com:oyatsugoro/intro.js.git                                           $# $@
register_remote .                                                             pasapsi                                  git@github.com:pasapsi/intro.js.git                                              $# $@
register_remote .                                                             pattle                                   git@github.com:pattle/intro.js.git                                               $# $@
register_remote .                                                             pboutin                                  git@github.com:pboutin/intro.js.git                                              $# $@
register_remote .                                                             peterkinmond                             git@github.com:peterkinmond/intro.js.git                                         $# $@
register_remote .                                                             pgherveou                                git@github.com:pgherveou/intro.js.git                                            $# $@
register_remote .                                                             phreezer                                 git@github.com:phreezer/intro.js.git                                             $# $@
register_remote .                                                             piascikj                                 git@github.com:piascikj/intro.js.git                                             $# $@
register_remote .                                                             pmosbach                                 git@github.com:pmosbach/intro.js.git                                             $# $@
register_remote .                                                             pra85                                    git@github.com:pra85/intro.js.git                                                $# $@
register_remote .                                                             puneetkay                                git@github.com:puneetkay/intro.js.git                                            $# $@
register_remote .                                                             qbolec                                   git@github.com:qbolec/intro.js.git                                               $# $@
register_remote .                                                             qixuan                                   git@github.com:qixuan/intro.js.git                                               $# $@
register_remote .                                                             raahede                                  git@github.com:raahede/intro.js.git                                              $# $@
register_remote .                                                             radicalgraphics                          git@github.com:radicalgraphics/intro.js.git                                      $# $@
register_remote .                                                             ragtek                                   git@github.com:ragtek/intro.js.git                                               $# $@
register_remote .                                                             ratbeard                                 git@github.com:ratbeard/intro.js.git                                             $# $@
register_remote .                                                             ratiw                                    git@github.com:ratiw/intro.js.git                                                $# $@
register_remote .                                                             rbsl-garima                              git@github.com:rbsl-garima/intro.js.git                                          $# $@
register_remote .                                                             redhataccess                             git@github.com:redhataccess/intro.js.git                                         $# $@
register_remote .                                                             renose                                   git@github.com:renose/intro.js.git                                               $# $@
register_remote .                                                             repos-javascript                         git@github.com:repos-javascript/intro.js.git                                     $# $@
register_remote .                                                             rhyous                                   git@github.com:rhyous/intro.js.git                                               $# $@
register_remote .                                                             richguan                                 git@github.com:richguan/intro.js.git                                             $# $@
register_remote .                                                             rickhanlonii                             git@github.com:rickhanlonii/intro.js.git                                         $# $@
register_remote .                                                             rnicholus                                git@github.com:rnicholus/intro.js.git                                            $# $@
register_remote .                                                             rockerest                                git@github.com:rockerest/intro.js.git                                            $# $@
register_remote .                                                             ronshoshani                              git@github.com:ronshoshani/intro.js.git                                          $# $@
register_remote .                                                             runn-vermel                              git@github.com:runn-vermel/intro.js.git                                          $# $@
register_remote .                                                             ryanhendry                               git@github.com:ryanhendry/intro.js.git                                           $# $@
register_remote .                                                             saasrobotics                             git@github.com:saasrobotics/intro.js_Archive.git                                 $# $@
register_remote .                                                             sailei1                                  git@github.com:sailei1/intro.js.git                                              $# $@
register_remote .                                                             saksoy                                   git@github.com:saksoy/intro.js.git                                               $# $@
register_remote .                                                             sayhiben                                 git@github.com:sayhiben/intro.js.git                                             $# $@
register_remote .                                                             schleim                                  git@github.com:schleim/intro.js.git                                              $# $@
register_remote .                                                             scraping                                 git@github.com:scraping/intro.js.git                                             $# $@
register_remote .                                                             sean8sean                                git@github.com:sean8sean/intro.js.git                                            $# $@
register_remote .                                                             shaharke                                 git@github.com:shaharke/intro.js.git                                             $# $@
register_remote .                                                             sharpnk                                  git@github.com:sharpnk/intro.js.git                                              $# $@
register_remote .                                                             shatyajeet                               git@github.com:shatyajeet/intro.js.git                                           $# $@
register_remote .                                                             shenmao1989                              git@github.com:shenmao1989/intro.js.git                                          $# $@
register_remote .                                                             shoonye                                  git@github.com:shoonye/intro.js.git                                              $# $@
register_remote .                                                             shoyan                                   git@github.com:shoyan/intro.js.git                                               $# $@
register_remote .                                                             shtoma                                   git@github.com:shtoma/intro.js.git                                               $# $@
register_remote .                                                             smappsnl                                 git@github.com:smappsnl/intro.js.git                                             $# $@
register_remote .                                                             spemoon                                  git@github.com:spemoon/intro.js.git                                              $# $@
register_remote .                                                             spmjs                                    git@github.com:spmjs/intro.js.git                                                $# $@
register_remote .                                                             sreckoo                                  git@github.com:sreckoo/intro.js.git                                              $# $@
register_remote .                                                             srinivas-dasari                          git@github.com:srinivas-dasari/intro.js.git                                      $# $@
register_remote .                                                             starsjz                                  git@github.com:starsjz/intro.js.git                                              $# $@
register_remote .                                                             stsbd                                    git@github.com:stsbd/intro.js.git                                                $# $@
register_remote .                                                             suan2046                                 git@github.com:suan2046/intro.js.git                                             $# $@
register_remote .                                                             sumit4iit                                git@github.com:sumit4iit/intro.js.git                                            $# $@
register_remote .                                                             suzannehamilton                          git@github.com:suzannehamilton/intro.js.git                                      $# $@
register_remote .                                                             sxau-web-team                            git@github.com:sxau-web-team/intro.js.git                                        $# $@
register_remote .                                                             takacsv                                  git@github.com:takacsv/intro.js.git                                              $# $@
register_remote .                                                             the0system                               git@github.com:the0system/intro.js.git                                           $# $@
register_remote .                                                             thestillbrandworks                       git@github.com:thestillbrandworks/intro.js.git                                   $# $@
register_remote .                                                             thorsteinsson                            git@github.com:thorsteinsson/intro.js.git                                        $# $@
register_remote .                                                             tomByrer                                 git@github.com:tomByrer/intro.js.git                                             $# $@
register_remote .                                                             trantorLiu                               git@github.com:trantorLiu/intro.js.git                                           $# $@
register_remote .                                                             tsmhome                                  git@github.com:tsmhome/Step-by-step-Intro.js.git                                 $# $@
register_remote .                                                             ttback                                   git@github.com:ttback/intro.js.git                                               $# $@
register_remote .                                                             tulku                                    git@github.com:tulku/intro.js.git                                                $# $@
register_remote .                                                             twocngdagz                               git@github.com:twocngdagz/intro.js.git                                           $# $@
register_remote .                                                             ubergrape                                git@github.com:ubergrape/intro.js.git                                            $# $@
register_remote .                                                             ulukfuni                                 git@github.com:ulukfuni/intro.js.git                                             $# $@
register_remote .                                                             unspongeful                              git@github.com:unspongeful/intro.js.git                                          $# $@
register_remote .                                                             usablica                                 git@github.com:usablica/intro.js.git                                             $# $@
register_remote .                                                             usablica-original                        git@github.com:usablica/intro.js.git                                             $# $@
register_remote .                                                             ustbtaotao                               git@github.com:ustbtaotao/intro.js.git                                           $# $@
register_remote .                                                             ustmaestro                               git@github.com:ustmaestro/intro.js.git                                           $# $@
register_remote .                                                             valkan78                                 git@github.com:valkan78/intro.js.git                                             $# $@
register_remote .                                                             venturepact                              git@github.com:venturepact/intro.js.git                                          $# $@
register_remote .                                                             vincentlaucy                             git@github.com:vincentlaucy/intro.js.git                                         $# $@
register_remote .                                                             vipero07                                 git@github.com:vipero07/intro.js.git                                             $# $@
register_remote .                                                             visense                                  git@github.com:visense/intro.js.git                                              $# $@
register_remote .                                                             vitorbal                                 git@github.com:vitorbal/intro.js.git                                             $# $@
register_remote .                                                             vkentta                                  git@github.com:vkentta/intro.js.git                                              $# $@
register_remote .                                                             voithos                                  git@github.com:voithos/intro.js.git                                              $# $@
register_remote .                                                             wang1001love                             git@github.com:wang1001love/intro.js.git                                         $# $@
register_remote .                                                             warjiang                                 git@github.com:warjiang/intro.js.git                                             $# $@
register_remote .                                                             waynn                                    git@github.com:waynn/intro.js.git                                                $# $@
register_remote .                                                             wilfrem                                  git@github.com:wilfrem/intro.js.git                                              $# $@
register_remote .                                                             wisesean                                 git@github.com:wisesean/intro.js.git                                             $# $@
register_remote .                                                             wizeline                                 git@github.com:wizeline/intro.js.git                                             $# $@
register_remote .                                                             wkylin                                   git@github.com:wkylin/intro.js.git                                               $# $@
register_remote .                                                             wtoscer                                  git@github.com:wtoscer/intro.js.git                                              $# $@
register_remote .                                                             xazzz                                    git@github.com:xazzz/intro.js.git                                                $# $@
register_remote .                                                             ximi                                     git@github.com:ximi/intro.js.git                                                 $# $@
register_remote .                                                             xkraty                                   git@github.com:xkraty/intro.js.git                                               $# $@
register_remote .                                                             yangnianbing                             git@github.com:yangnianbing/intro.js.git                                         $# $@
register_remote .                                                             ye11ow                                   git@github.com:ye11ow/intro.js.git                                               $# $@
register_remote .                                                             yejingfu                                 git@github.com:yejingfu/intro.js.git                                             $# $@
register_remote .                                                             yesseecity                               git@github.com:yesseecity/intro.js.git                                           $# $@
register_remote .                                                             yevolcn                                  git@github.com:yevolcn/intro.js.git                                              $# $@
register_remote .                                                             yifanes                                  git@github.com:yifanes/intro.js.git                                              $# $@
register_remote .                                                             yuichi-akimoto                           git@github.com:yuichi-akimoto/intro.js.git                                       $# $@
register_remote .                                                             yuvale                                   git@github.com:yuvale/intro.js.git                                               $# $@
register_remote .                                                             zanderle                                 git@github.com:zanderle/intro.js.git                                             $# $@



popd                                                                            2> /dev/null   > /dev/null

